# dlogger configuration file
# Lines starting with # are comments.
# Key and value are separated by spaces, tabs, or =.
# Exclude paths can be separated by colons (:) or commas (,).

FINE_EXCLUDE_PATH = /etc/:/sys/:/proc/:/dev/:/run/
