#!/bin/bash
# It would be great if you can compile without root privilege, but the
# toolchain is so broken that it dumps a ton of errors on correct programs.

wrapper="sudo time"
if (( `id -u` == 0 )); then
    wrapper=exec
fi
$wrapper ./eauditd.py  -l ./eauditd.so "$@"
